### ISSUE TITLE
medical_prescription_state_verify: Error installing

### ISSUE THREAD

**Issue by kellylougheed** [LasLabs/vertical-medical#149]
Even though medical_prescription_state_verify has "installable: False," I tried installing it and got this error:

  File "/opt/odoo/odoo/models.py", line 521, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'medical.prescription.order.state' does not exist in registry.

**Comment by lasley** [comment]
Bah I forgot about this module. We'll need to upgrade it, it was an SMD request originally.

Some of the logic from here was moved into:
* https://github.com/LasLabs/vertical-medical/tree/release/10.0/medical_prescription_state

But some of the logic from `medical_prescription_state` was moved to:
* https://github.com/OCA/server-tools/tree/10.0/base_kanban_stage

One piece that was removed was a state to stage mapping. We need to use the stages directly instead, because it is more scalable.
