### ISSUE TITLE
Merge module 'medical' to OCA -- conflicts

### ISSUE THREAD

**Issue by JordiBForgeFlow** [LasLabs/vertical-medical#206]
Hi!

We would like to start bringing the modules that we review from LasLabs/release/10.0 to OCA/10.0.

I tried with module 'medical', with unhappy results.

I have tried to do it using the same procedure as I would do to migrate a module between OCA versions:
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

But the results are messy. It seems that both branches have diverged in their own lifecycle.

At this point, I am considering to just create a PR to OCA with a copy-paste of the module from release/10.0, and put your team as author. It is ugly, but I am not sure what else can be done.

**Comment by lasley** [comment]
Ah yes this is a cluster - we've diverged drastically. I'll bring `medical` over sometime today and tag you in the PR. The ugly solution is what we were planning too - my team isn't worried about their individual attribution. 

The main thing holding us back was #123, which is to strip out some AGPL functionality into an explicit AGPL package. This was the compromise to using some of the OCA ecosystem while still allowing LGPL. It wasn't an issue in v9 because the specific functionality was included directly in vertical-medical but was later found to be duplicating existing modules.

Side note - Interesting timing on your part - these tickets just came up in our sprint that started yesterday, so I don't even have to break sprint to do it!

**Comment by lasley** [comment]
Closing to track in PRs OCA#173 & OCA#174. Once those are merged, we'll submit the next layer of [dependencies](https://github.com/OCA/vertical-medical/wiki#dependency-graph).
