### ISSUE TITLE
2 display issues in the patient diseases form

### ISSUE THREAD

**Issue by jcdrubay** [LasLabs/vertical-medical#78]
- A lot of extra white space on the right of the form
- Bonus footer

![image](https://cloud.githubusercontent.com/assets/1765420/21639524/1e9bb7b2-d2a3-11e6-885f-e1feff3df936.png)

**Comment by lasley** [comment]
Ugh yeah that footer is something I've been battling with since starting in VM. For some reason nearly every view contained this "configurator" section at the bottom, all with this fairly useless meta information. Keep an eye out for them - you will only see when you are a user with Medical Configurator rights & I think debug mode needs to be on.
