### ISSUE TITLE
Validation error when creating a sale from a prescription

### ISSUE THREAD

**Issue by kellylougheed** [LasLabs/vertical-medical#91]
Error while validating constraint
Conversion from Product UoM g to Default UoM Unit(s) is not possible as they both belong to different Category!.

**Comment by lasley** [comment]
Hi @kellylougheed - This one is expected, although maybe we should clarify the error a bit. Maybe a workflow enhancement too if we can identify the spot for a default or something.

Units of measure need to be of the same class in order to be converted. In this instance, the UoM on the product is `g`, but the prescription line looks to have been the default UoM of `unit`. A gram can't be converted to a unit.

The field you're looking for on the Rx Line is "Dispense UoM". Looking at the Rx line form, it seems that the top part is squished into a single column - which probably doesn't help with seeing all the fields.

**Comment by woodbrettm** [comment]
@kellylougheed what steps did you take to bring up that error message, and do you have sale_stock_medical_prescription installed? Or just sale_medical_prescription?

**Comment by lasley** [comment]
The error is identified @bmw95, the steps taken was not entering a Dispense UoM in the prescription line when creating it.

I'm thinking an onchange to switch the UoM when medicament is switched.

**Comment by kellylougheed** [comment]
Just retested it -- it works when entering a Dispense UoM!

**Comment by woodbrettm** [comment]
@lasley sure thing. Reason I asked was there's something similar in [oca/vertical-medical](https://github.com/OCA/vertical-medical/pull/89) that I'm working on addressing so thought this may have been related.
